"""empty message

Revision ID: 472ba2ebb122
Revises: ea63eac1cddd
Create Date: 2026-01-14 01:25:40.333808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472ba2ebb122'
down_revision = 'ea63eac1cddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_slots', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('parking_slots')

    # ### end Alembic commands ###
