"""Add SystemConfig table

Revision ID: 9798ba24ee89
Revises: 9c7812bb620d
Create Date: 2026-01-13 19:49:07.674646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9798ba24ee89'
down_revision = '9c7812bb620d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('use_ocr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_ocr', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
