"""empty message

Revision ID: ea63eac1cddd
Revises: c2f335c05b1e
Create Date: 2026-01-14 01:10:57.773932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea63eac1cddd'
down_revision = 'c2f335c05b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_record', schema=None) as batch_op:
        batch_op.drop_column('plate_type')

    # ### end Alembic commands ###
